apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecomm
  labels:
    app: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: michealken30/backend-api:latest
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-uri
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: secret-key
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: stripe-secret-key
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: email
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: email-password

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ecomm
spec:
  selector:
    app: backend
  ports:
    - port: 4000
      protocol: TCP
  type: ClusterIP
